#!/bin/bash

files_to_remove=(
    /usr/bin/opbitrate
    /usr/share/enigma2/xDreamy
    /usr/lib/enigma2/python/Plugins/Extensions/xDreamy
    /usr/lib/enigma2/python/Components/Converter/iAccess.py
    /usr/lib/enigma2/python/Components/Converter/iBase.py
    /usr/lib/enigma2/python/Components/Converter/iBitrate.py
    /usr/lib/enigma2/python/Components/Converter/iBitrate3.py
    /usr/lib/enigma2/python/Components/Converter/iBoxInfo.py
    /usr/lib/enigma2/python/Components/Converter/iCaidInfo2.py
    /usr/lib/enigma2/python/Components/Converter/iCamdRAED.py
    /usr/lib/enigma2/python/Components/Converter/iCpuUsage.py
    /usr/lib/enigma2/python/Components/Converter/iCryptoInfo.py
    /usr/lib/enigma2/python/Components/Converter/iEcmInfo.py
    /usr/lib/enigma2/python/Components/Converter/iEventList.py
    /usr/lib/enigma2/python/Components/Converter/iEventName2.py
    /usr/lib/enigma2/python/Components/Converter/iExtra.py
    /usr/lib/enigma2/python/Components/Converter/iExtraNumText.py
    /usr/lib/enigma2/python/Components/Converter/iFrontendInfo.py
    /usr/lib/enigma2/python/Components/Converter/iInfoEvent.py
    /usr/lib/enigma2/python/Components/Converter/iMenuDescription.py
    /usr/lib/enigma2/python/Components/Converter/iMenuEntryCompare.py
    /usr/lib/enigma2/python/Components/Converter/iNetSpeedInfo.py
    /usr/lib/enigma2/python/Components/Converter/iNextEvents.py
    /usr/lib/enigma2/python/Components/Converter/iReceiverInfo.py
    /usr/lib/enigma2/python/Components/Converter/iRouteInfo.py
    /usr/lib/enigma2/python/Components/Converter/iServName2.py
    /usr/lib/enigma2/python/Components/Converter/iTemp.py
    /usr/lib/enigma2/python/Components/Converter/iVpn.py
	/usr/lib/enigma2/python/Components/Converter/xDreamy_AlwaysTrue.py
	/usr/lib/enigma2/python/Components/Converter/xDreamy_AudioInfo.py 
	/usr/lib/enigma2/python/Components/Converter/xDreamy_ECMInfo.py
	/usr/lib/enigma2/python/Components/Converter/xDreamy_HideAtTimeshift.py
	/usr/lib/enigma2/python/Components/Converter/xDreamy_IPChecker.py
	/usr/lib/enigma2/python/Components/Converter/xDreamy_ServiceInfoEX.py
	/usr/lib/enigma2/python/Components/Converter/xDreamy_ServiceInfoEX2.py
	/usr/lib/enigma2/python/Components/Converter/xDreamy_ServiceName2.py
	/usr/lib/enigma2/python/Components/Converter/xDreamy_TextTranslator.py
	/usr/lib/enigma2/python/Components/Converter/xDreamy_UTIPdata.py
	/usr/lib/enigma2/python/Components/Converter/xDreamyinfoMovie.py
    /usr/lib/enigma2/python/Components/Renderer/iBackdropX.py
    /usr/lib/enigma2/python/Components/Renderer/iBackdropXDownloadThread.py
    /usr/lib/enigma2/python/Components/Renderer/iChannelNumber.py
    /usr/lib/enigma2/python/Components/Renderer/iEmptyEpg.py
    /usr/lib/enigma2/python/Components/Renderer/iEventListDisplay.py
    /usr/lib/enigma2/python/Components/Renderer/iGenre.py
    /usr/lib/enigma2/python/Components/Renderer/iInfoEvents.py
    /usr/lib/enigma2/python/Components/Renderer/iNxtEvnt.py
    /usr/lib/enigma2/python/Components/Renderer/iParental.py
    /usr/lib/enigma2/python/Components/Renderer/iPosterX.py
    /usr/lib/enigma2/python/Components/Renderer/iPosterXDownloadThread.py
    /usr/lib/enigma2/python/Components/Renderer/iPosterXEMC.py
    /usr/lib/enigma2/python/Components/Renderer/iRunningText.py
    /usr/lib/enigma2/python/Components/Renderer/iSingleEpgList.py
    /usr/lib/enigma2/python/Components/Renderer/iStarX.py
    /usr/lib/enigma2/python/Components/Renderer/iVolume2.py
    /usr/lib/enigma2/python/Components/Renderer/iVolumeText.py
    /usr/lib/enigma2/python/Components/Renderer/iVolz.py
    /usr/lib/enigma2/python/Components/Renderer/iWatches.py
    /usr/lib/enigma2/python/Components/Converter/iServicePosition.py
	/usr/lib/enigma2/python/Components/Renderer/xDreamy_AnimatedMoonPixmap.py
	/usr/lib/enigma2/python/Components/Renderer/XDreamy_AudioIcon.py
	/usr/lib/enigma2/python/Components/Renderer/xDreamy_flipclock_infobars_gelb.py
	/usr/lib/enigma2/python/Components/Renderer/xDreamy_mod_flipclock_infobars_gelb.py
	/usr/lib/enigma2/python/Components/Renderer/xDreamy_mod_PiconUni.py
	/usr/lib/enigma2/python/Components/Renderer/xDreamy_mod_PiconUni_2.py
	/usr/lib/enigma2/python/Components/Renderer/xDreamy_parentalEvent.py
	/usr/lib/enigma2/python/Components/Renderer/XDreamy_PicCript2.py
	/usr/lib/enigma2/python/Components/Renderer/xDreamy_PicEmu2.py
	/usr/lib/enigma2/python/Components/Renderer/xDreamy_PiconUni.py
	/usr/lib/enigma2/python/Components/Renderer/xDreamy_poster.py
	/usr/lib/enigma2/python/Components/Renderer/xDreamy_PosterX.py
	/usr/lib/enigma2/python/Components/Renderer/xDreamy_UTIPflag.py
	/usr/lib/enigma2/python/Components/Renderer/xDreamy_XPicon.py
	/usr/lib/enigma2/python/Components/Renderer/xDreamy_ZZPicon.py
	/usr/lib/enigma2/python/Components/Renderer/xDreamy2_AnimatedMoonPixmap.py
)

for file in "${files_to_remove[@]}"; do
    rm -rf "$file" > /dev/null 2>&1
done
echo "   "
echo 'XDREAMY Skin Package removed successfully.'
echo "   "
sleep 2
exit 0
