#!/bin/sh
echo "   "
echo "------------------------------------------------------------------------"
echo "                            Welcome To XDREAMY_mod                          "
echo "                         XDREAMY Skin By Inspiron                       "
echo "                       Don't Remove this Disclaimer                     "
echo "------------------------------------------------------------------------"
echo "          Experience Enigma2 skin like never before with XDREAMY_mod        "
echo "------------------------------------------------------------------------"
sleep 2
echo "  "
echo "You are going to install XDREAMY_mod skin, please wait...      "
status='/var/lib/opkg/status'
package='enigma2-plugin-skins-xDreamy_mod'

if grep -q $package $status; then
opkg remove $package > /dev/null 2>&1
fi
if [ -d /control ] ; then
rm -rf /control  > /dev/null 2>&1
fi
if [ -d /CONTROL ] ; then
rm -rf /CONTROL  > /dev/null 2>&1
fi
if [ -f /Control ] ; then
rm -rf /Control  > /dev/null 2>&1
fi
exit 0
